services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swapi-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swapi-scheduler
    restart: unless-stopped
    command: php artisan schedule:work
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
      - backend

  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swapi-queue
    restart: unless-stopped
    command: php artisan queue:work --tries=3
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
      - backend

  nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: swapi-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - nginx

  mysql:
    image: mysql:8.0-debian
    platform: linux/amd64
    container_name: swapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swapi
      MYSQL_USER: swapi
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-swapi-data:/var/lib/mysql
  
volumes:
    mysql-swapi-data: